CREATE TABLE URL
(
    ID SERIAL PRIMARY KEY,
    ORIGINAL_URL VARCHAR(255) NOT NULL,
    SHORT_URL VARCHAR(255) NOT NULL,
    DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ACCESS (
    ID SERIAL PRIMARY KEY,
    URL_ID INTEGER NOT NULL,
    DATE_ACCESS TIMESTAMP NOT NULL,
    FOREIGN KEY (URL_ID) REFERENCES URL(ID)
);